repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
    exclude: '^comet/core/migrations/.*'

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.291
  hooks:
  - id: ruff
    exclude: '^comet/core/migrations/.*'

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    exclude: '^comet/core/migrations/.*'

- repo: https://github.com/djlint/djLint
  rev: v1.34.1
  hooks:
    - id: djlint-reformat-jinja
      files: theme

- repo: local
  hooks:
    - id: prettier
      name: prettier
      language: node
      entry: prettier --write
      additional_dependencies: ["prettier"]
      files: '.*.js$'
